PARIS01:
  - BSD-248magl
  - CBW-200magl
  - CSP-10magl
  - HFD-100magl
  - MHD-10magl
  - MLH-10magl
  - RGL-90magl
  - TAC-185magl
  - TTA-222magl
  - VAL-10magl
  - WAO-20magl
  - BRM-212magl
  - BIR-75magl
  - CMN-500magl
  - GAT-341magl
  - HEI-30magl
  - HEL-110magl
  - HPB-131magl
  - HTM-150magl
  - HUN-115magl
PARIS02:
  - JFJ-5magl
  - KIT-200magl
  - KRE-250magl
  - LIN-98magl
  - LUT-60magl
  - NOR-100magl
  - OPE-120magl
  - OXK-163magl
  - PAL-10magl
  - SAC-100magl
  - SMR-125magl
  - SSL-12magl
  - STE-252magl
  - TOB-12magl
  - TOH-147magl
  - TRN-180magl
  - UTO-57magl
  - WES-14magl
  - ZEP-10magl
  - ZSF-3magl
